# Generated by Django 5.0.3 on 2024-06-11 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0002_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='Sent_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
